services:
  patient-service-db:
    image: postgres:16-alpine
    container_name: patient-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-patient_service_db}
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
      # Mount initialization script into entrypoint directory
      - ./init-scripts/patient_dummy_data.sql:/docker-entrypoint-initdb.d/01-patient_dummy_data.sql
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-patient_service_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - internal

  patient-service:
    build:
        context: ./patient-service
        dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/{POSTGRES_DB:-patient_service_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_PORT: 9001
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Disable Spring SQL initialization since PostgreSQL handles it
      SPRING_SQL_INIT_MODE: "never"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRINGDOC_API_DOCS_ENABLED: ${SPRINGDOC_API_DOCS_ENABLED:-true}
      SPRINGDOC_SWAGGER_UI_ENABLED: ${SPRINGDOC_SWAGGER_UI_ENABLED:-true}
    networks:
      - internal
    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
      billing-service:
        condition: service_started

  billing-service:
    build:
        context: ./billing-service
        dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

volumes:
  patient-service-db-data:

networks:
  internal:
    driver: bridge
    external: true