spring.application.name=patient-service
server.port=4000

## Spring Kafka Configuration
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

## H2 Database Configuration

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

## Logging Configuration
logging.level.root=INFO


## Swagger Configuration
#springdoc.api-docs.enabled=true
## Expose the Swagger UI at /swagger-ui.html
#springdoc.swagger-ui.enabled=true
